package:
  name: meld-cuda{{ CUDA_SHORT_VERSION }}
  version: "0.4.15"

source:
  git_url: https://github.com/maccallumlab/meld.git
  git_rev: 0.4.15

build:
  number: 0
  skip: True # [win]
  script_env:
    - CUDA_VERSION
    - CUDA_SHORT_VERSION
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - DOCDEPLOY

requirements:
  build:
    - openmm-cuda{{ CUDA_SHORT_VERSION }} ==7.2.2
    - cmake
    - doxygen # [not osx]
    - python
    - swig
    - eigen3
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - sphinx
    - sphinx_rtd_theme
    - mpi4py ==2.0.0
    - clangdev ==6.0.0
    - awscli
    - breathe
    - mypy
    - parmed


  run:
    - python
    - openmm-cuda{{ CUDA_SHORT_VERSION }} ==7.2.2
    - ambermini
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - mpi4py ==2.0.0
    - scikit-learn >=0.18.0
    - parmed

test:
  imports:
    - meld
    - meldplugin
  commands:
    - python -m unittest discover meld.test

about:
    home: https://meldmd.org
